version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./frontend  # Путь к директории с фронтендом
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

  api:
      build:
        context: ./api  # Путь к директории с бэкендом
      ports:
        - "8000:8000"
      volumes:
        - ./api:/app
      environment:
        - NODE_ENV=production
      depends_on:
        - mongo

volumes:
  mongo-data:
